#!/usr/bin/env bash
cd Monsters
echo -e "\e[33m          _____ ____  _   _    _    _  _______\e[0m"
echo -e "\e[33m          / ____|\e[0m"
echo -e "\e[33m           _|\e[0m"
echo -e "\e[33m           _ \| . \| |___\e[0m"
echo -e "\e[33m           |_| |____/|_| |_/_/   \_\_|\_\_____|\e[0m"
while(true) do
lua start.lua 
done
